version: '3.2'

networks:
  assessment-network:

services:
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment-db
    restart: on-failure
    ports:
      - '5432:5432'
    networks:
      - assessment-network