version: "3.2"

networks:
  assessment-network:

services:
  app:
    build: .
    restart: always
    ports:
      - "2565:2565"
    environment:
      DATABASE_URL: postgres://root:root@db:5432/assessment-prod-db?sslmode=disable
      PORT: 2565
    depends_on:
      - db
    networks:
      - assessment-network

  db:
    image: postgres:12.12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment-prod-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - assessment-network