version: "3.2"

networks:
  assessment-test-network:

services:
  test_app:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/target
    environment:
      DATABASE_URL: postgres://root:root@test_db:5432/assessment-test-db?sslmode=disable
      PORT: 2565
    depends_on:
      - test_db
    networks:
      - assessment-test-network

  test_db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment-test-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - assessment-test-network
