version: "3.2"

networks:
  assessment-test-network:

services:
  test_app:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - test_db
    networks:
      - assessment-test-network

  test_db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment-db
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - assessment-test-network
