FROM golang:1.19-alpine

WORKDIR /go/src/target

CMD CGO_ENABLED=0 go test --tags=integration ./... -cover -coverprofile=coverage/cover.out && \
	go tool cover -html=coverage/cover.out -o coverage/coverage.html